### ISSUE TITLE
Installer not working

### ISSUE THREAD

**Issue by darinhouston** [dstuecken/ddj-800-big-sur-installer#1]
Somewhat urgent to get working as I bought DDJ-800 for my son for XMAS and he's upgraded to Big Sur already.  Installer won't run - opens a Terminal session, tries to run shell script but error "No such file or directory".  This seems to be some sort of AppleScript problem as it's trying to launch from some path in /private/var...  When I try to run the bash script manually, it runs cleanly and reboots.  But, no joy from the Driver Version Display Utility.  

Says "There is a problem with the driver configuration.  Please reinstall the drivers."

System Profile showed a hardware interface for DDJ800 at one point, but after a few attempts it's not now there.  I also tried to walk through the script commands manually and that isn't working either.

Any thoughts?

**Comment by darinhouston** [comment]
I moved it to /Library/Extensions and repaired ownership/permissions and it seemed to load but doesn't show up in System Information or confirmed in version app.  It is available in audio drop-down and in audio section of Rekordbox, however controller says no driver and it is non-responsive.

**Comment by dstuecken** [comment]
Does your Mac have the new M1 chip? The Pioneer driver is not compatible with M1 unfortunately. 

> There is a problem with the driver configuration. Please reinstall the drivers.

It says that for me as well until I plugin the DDJ-800!

**Comment by dstuecken** [comment]
I just fixed the No such file or directory issue, can you try to redownload the installer and open the Install script again ?

**Comment by darinhouston** [comment]
> I just fixed the No such file or directory issue, can you try to redownload the installer and open the Install script again ?

Thanks - I'll try that.  To answer your previous question, no - I just purchased an M1 (which rocks by the way) but this is my son's older Air which is Intel.

**Comment by darinhouston** [comment]
Still not working -- 

Last login: Sat Dec 26 09:39:58 on ttys000

The default interactive shell is now zsh.
To update your account to use zsh, please run `chsh -s /bin/zsh`.
For more details, please visit https://support.apple.com/kb/HT208050.

Maxwells-Air:~ max$ /bin/bash /private/var/folders/sj/c1q60zyd2h38mmlc35dby8z40000gn/T/AppTranslocation/75B69493-3F31-41E5-8306-CEB33099669D/dSource/install-ddj-800.sh
/bin/bash: /private/var/folders/sj/c1q60zyd2h38mmlc35dby8z40000gn/T/AppTranslocation/75B69493-3F31-41E5-8306-CEB33099669D/dSource/install-ddj-800.sh: No such file or directory

**Comment by darinhouston** [comment]
I went through and manually entered all the commands from the command line.  This time the kextload gave me an error only that a reboot was required and I rebooted.  kextstat showed nothing from pioneer, so I issued the kextload command again.  Now, the driver shows in the kextstat and survives a reboot.  But, controller still shows "No Audio Driver" and the VersionViewer still shows something wrong with the audio driver.  Looking at System Information, DDJ800 is listed in the USB section.  

So, Installer aside, still no joy.

I'm anxious to get it at least minimally working to confirm the controller is in good working order since we bought it from Reverb and have only a short time to confirm it arrived in working order.

**Comment by fmatzy** [comment]
I bought DDJ-800 yesterday and tried this installer. I also got the error `No such file or directory`.

I ran the file `install-ddj-800.sh` directly. I allowed some dialogs, allowed the installed driver in System Preferences-> Security & Privacy, and rebooted. The driver was not enabled at this point, but when I ran `install-ddj-800.sh` again, though VersionViewer still shows something wrong with the audio driver, DDJ-800 was recognized successfully.

Thanks to @dstuecken and I hope this comment helps @darinhouston.
